# -*- coding: utf-8 -*-
"""ResumeIQ.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qcazd8-8wKwsexiH3JFHHWQ4n8E_QkBI
"""

!pip install pymupdf

# =========================
# ResumeIQ — AI Career Intelligence Platform (FIXED VERSION)
# =========================

import gradio as gr
import fitz  # PyMuPDF

# =========================
# DATA
# =========================
SKILLS = [
    "python", "sql", "excel", "power bi",
    "machine learning", "data analysis",
    "communication", "project management",
    "html", "css", "javascript", "react"
]

ROLE_MAP = {
    "data analyst": ["sql", "excel", "power bi", "data analysis"],
    "web developer": ["html", "css", "javascript", "react"],
    "ai engineer": ["python", "machine learning", "data analysis"]
}

# =========================
# RESUME PARSER (FIXED)
# =========================
def extract_text(pdf_file):
    if pdf_file is None:
        return ""

    text = ""

    # ✅ FIX: Gradio gives file path when type="filepath"
    if isinstance(pdf_file, str):
        doc = fitz.open(pdf_file)

    elif hasattr(pdf_file, "name"):
        doc = fitz.open(pdf_file.name)

    elif hasattr(pdf_file, "read"):
        doc = fitz.open(stream=pdf_file.read(), filetype="pdf")

    else:
        doc = fitz.open(str(pdf_file))

    for page in doc:
        text += page.get_text()

    return text.lower()

# =========================
# ATS ENGINE
# =========================
def ats_analysis(text):
    found, missing = [], []

    for skill in SKILLS:
        if skill in text:
            found.append(skill)
        else:
            missing.append(skill)

    score = int((len(found) / len(SKILLS)) * 100)
    return score, found, missing

# =========================
# JOB MATCH ENGINE
# =========================
def match_job(text, role):
    keywords = ROLE_MAP.get(role.lower(), [])

    if not keywords:
        return role, 0, [], ["Role not supported"]

    matched = [k for k in keywords if k in text]
    missing = [k for k in keywords if k not in text]

    score = int((len(matched) / len(keywords)) * 100)

    return role, score, matched, missing

# =========================
# RESUME REWRITER
# =========================
def rewrite(text):
    rules = {
        "worked": "developed",
        "did": "executed",
        "made": "built",
        "helped": "assisted",
        "good": "strong",
        "create": "designed"
    }

    for k, v in rules.items():
        text = text.replace(k, v)

    return text

# =========================
# MAIN DASHBOARD
# =========================
def dashboard(file, role):

    try:
        text = extract_text(file)

        if not text.strip():
            return (
                "❌ No text found in resume",
                "❌ Upload valid PDF resume",
                "❌ Cannot process resume"
            )

        ats_score, found, missing = ats_analysis(text)
        role_name, match_score, matched, role_missing = match_job(text, role)
        improved = rewrite(text)

        ats_card = f"""
🧠 ATS SCORE DASHBOARD
────────────────────────
Score: {ats_score}/100

🟢 Found Skills:
{', '.join(found) if found else 'None'}

🔴 Missing Skills:
{', '.join(missing) if missing else 'None'}

Status: {'STRONG PROFILE' if ats_score > 70 else 'NEEDS IMPROVEMENT'}
"""

        match_card = f"""
🎯 JOB MATCH ANALYSIS
────────────────────────
Role: {role_name}

Match Score: {match_score}/100

🟢 Matched:
{', '.join(matched) if matched else 'None'}

🔴 Missing:
{', '.join(role_missing) if role_missing else 'None'}

Verdict: {'GOOD FIT' if match_score > 60 else 'LOW MATCH'}
"""

        resume_card = f"""
✨ AI REWRITTEN RESUME
────────────────────────
{improved[:2500]}
"""

        return ats_card, match_card, resume_card

    except Exception as e:
        return (
            f"❌ ERROR: {str(e)}",
            f"❌ ERROR: {str(e)}",
            "❌ PROCESS FAILED"
        )

# =========================
# UI
# =========================
ui = gr.Blocks(theme=gr.themes.Soft())

with ui:

    gr.Markdown("""
<div style="
padding:40px;
border-radius:30px;
text-align:center;
background: linear-gradient(120deg,#0f172a,#1e293b,#334155);
color:white;
">

<h1 style="font-size:56px;margin:0;">
🧠 ResumeIQ
</h1>

<p style="font-size:22px;margin-top:10px;">
AI-Powered Resume Intelligence
</p>

<p style="opacity:0.85;">
Analyze Skills • Match Jobs • Improve Resumes
</p>

</div>

<br>

<div style="display:flex;justify-content:center;gap:15px;flex-wrap:wrap;">

<div style="
padding:15px 25px;
border-radius:999px;
background:#2563eb;
color:white;
">
📊 ATS Score
</div>

<div style="
padding:15px 25px;
border-radius:999px;
background:#16a34a;
color:white;
">
🎯 Role Match
</div>

<div style="
padding:15px 25px;
border-radius:999px;
background:#9333ea;
color:white;
">
✨ AI Rewrite
</div>

</div>
""")

    with gr.Row():

        with gr.Column(scale=1):
            gr.Markdown("## 📂 Upload Panel")
            file = gr.File(label="Upload Resume PDF", type="filepath")  # ✅ FIX HERE
            role = gr.Textbox(label="Target Role (e.g. data analyst)")
            btn = gr.Button("🚀 Analyze Resume")

        with gr.Column(scale=2):
            gr.Markdown("## 📊 AI Dashboard Output")

            ats_out = gr.Textbox(label="ATS Analysis", lines=12)
            match_out = gr.Textbox(label="Job Match Analysis", lines=12)
            resume_out = gr.Textbox(label="AI Rewritten Resume", lines=15)

    btn.click(
        fn=dashboard,
        inputs=[file, role],
        outputs=[ats_out, match_out, resume_out]
    )

ui.launch()

